### ISSUE TITLE
Add timestamp for continously rebuilds with the watcher in the console output

### ISSUE THREAD

**Issue by cwasser** [trivago/parallel-webpack#12]
It would be nice, if you could also add an time stamp for the current build to the console output for the continously rebuilds via the watcher. If you running the watcher for a long time, then it is easy to loose the overview of your rebuilds. 
Sometimes I am not sure when I am touching some code and the watcher is turned on, if the latest changes are already built or are still in building.

Best regards,
Chris

**Comment by pago** [comment]
Will be published with the next release.

**Comment by pago** [comment]
Version 1.4.0 has just been published which adds support for this feature. :)

**Comment by cwasser** [comment]
Nice, thx for the enhancement @pago :)
