### ISSUE TITLE
Add config extension interpretation for ".babel.js", ".coffee", etc

### ISSUE THREAD

**Issue by arianrhodsandlot** [trivago/parallel-webpack#13]
I use a `webpack.config.babel.js` as my webpack config file, and now I'm trying to use parallel-webpack with this project.

Webpack supports config files those named `webpack.config.babel.js` or `webpack.config.coffee`. As I see,  this nice feature comes from [js-interpret](https://github.com/js-cli/js-interpret). Could parallel-webpack add interpretation for these too?

**Comment by pago** [comment]
Very nice idea. Thanks for suggesting it and doing all the research!
I'll include it for the next version.

**Comment by pago** [comment]
Implemented in version 1.4.0 (released a few seconds ago). Was a bit trickier than I expected but works quite well now. Thanks again for the suggestion!
