### ISSUE TITLE
Please use a changelog

### ISSUE THREAD

**Issue by valscion** [trivago/parallel-webpack#15]
Hi!

Thanks for this package, it seems quite nice and we've sometimes used it in our projects.

It would help a lot in upgrading if you had a changelog I could view. You can generate one with https://github.com/skywinder/github-changelog-generator to provide some baseline which wouldn't take much time.

**Comment by pago** [comment]
Thanks a lot. I've been using https://github.com/conventional-changelog/conventional-changelog for internal projects for a while now and intended to set it up for use here as well. Do you think that'd be preferable or should I use the tool you've linked (which looks very nice as well)?

**Comment by valscion** [comment]
I don't have strong feelings one way or the other, any changelog that is better than just `git log` would be great :smile:

**Comment by valscion** [comment]
Hooray, thank you! 💞
