### ISSUE TITLE
Can you support --bail and --json flags?

### ISSUE THREAD

**Issue by volkanunsal** [trivago/parallel-webpack#2]
My current build requires these two flags provided by the `webpack` binary. Is there some way I can get the same effect from `parallel-webpack`? Here is the full command:

```bash
$(npm bin)/webpack --colors --config config/webpack/production.config.js --json --bail 2>&1
```

**Comment by pago** [comment]
Sure, it shouldn't be too tricky to implement those flags. `--json` is almost there, I just need to implement the dumping and make sure the stats are actually propagated back properly.
`--bail` might be a bit more tricky but should also be possible. But just to be sure that the correct behaviour is implemented: If one of the parallel webpacks fails, the entire build should fail and all other builds should be stopped immediately. Right?

Thank you for the feedback!

**Comment by volkanunsal** [comment]
> If one of the parallel webpacks fails, the entire build should fail and all other builds should be stopped immediately. Right?

Yes, that would be the ideal scenario.

**Comment by pago** [comment]
Added support for the `--json` flag and limited support for `--bail`. Unfortunately, we can't quit running processes when one of the others fails, instead, we simply stop scheduling new ones and don't start those which haven't been started already.
As that was already the default behaviour, I've chosen to specify `--bail` as the default option but added the possibility to deactivate it.

This change has been released as version 1.1.0.

Please let me know if you need any other adjustments. Thanks!

**Comment by volkanunsal** [comment]
One minor thing. The output of the command is an array, but Webpack command returns a JSON string. Otherwise the interface is compatible.

**Comment by pago** [comment]
In order to do that, we'd have to merge the output objects. If you're familiar with the exact structure that Webpack generates, perhaps you could send in a merge request or provide some details? Or even just a small test case that I can use to verify that the output is what you expect it to be?
