### ISSUE TITLE
EventEmitter memory leak warnings

### ISSUE THREAD

**Issue by perry-mitchell** [trivago/parallel-webpack#22]
I get a huge amount EventEmitter warnings when running with either Webpack 1.x or 2.x:

```
(node:10856) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10867) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10856) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10867) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10856) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10855) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10867) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10855) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10856) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10849) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:10849) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10867) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10855) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10849) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10855) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:10849) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

I'm using NodeJS 6.8.1 on Ubuntu 16.04 with parallel-webpack 1.5.0. I do not get any warnings running webpack normally.

I imagine that these items may be the cause:

 * https://github.com/trivago/parallel-webpack/blob/master/src/webpackWorker.js#L135
 * https://github.com/trivago/parallel-webpack/blob/cd78da582145e2c8b65f63e30d7331ef3dfec421/index.js#L81

I suspect that there's no real issue here, but the warnings are unsightly. Very happy that it works with Webpack2.

**Comment by pago** [comment]
Interesting. You're right, its not a "real" issue as those listeners are necessary to shutdown the processes when you exit the process from the command line but we should definitely avoid those warnings. Would you like to submit a pull request for this?

**Comment by perry-mitchell** [comment]
@pago Since creating this issue it also seems that I get complaints from webpack in general that are _similar_ to this. I'll file a bug/MR there if I can.. it may not be anything to do with parallel-webpack.

**Comment by pago** [comment]
Could you link the issue/MR here once it exists so we can keep track of how it goes? In case its produced by `parallel-webpack` I'd like to make sure we fix it which is a lot easier with that link.

Thank you!

**Comment by perry-mitchell** [comment]
Seems that it's not an issue with webpack directly, but with plugins such as image-webpack-loader. It's maginified in parallel-webpack due to the workers, but it has nothing to do with this repo.

It's traceable deep down the dependency ladder:
```
(node:7783) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at EventEmitter.addListener (events.js:275:10)
    at module.exports (/home/perry/work/kiosked-js/node_modules/signal-exit/index.js:41:11)
    at module.exports.err (/home/perry/work/kiosked-js/node_modules/execa/index.js:146:23)
    at fsP.writeFile.then (/home/perry/work/kiosked-js/node_modules/exec-buffer/index.js:35:15)
```

And it seems to be an issue with the package execa (calling signal-exit): https://github.com/sindresorhus/execa/issues/61

Seems that even when it gets fixed, it'll be some time for it to propagate. I'll reopen an issue here if a fix is made and I can start to help update various packages.
