### ISSUE TITLE
Don't have options propagation to worker-farm expect: 'maxConcurrentWorkers' and 'maxRetries'

### ISSUE THREAD

**Issue by wKich** [trivago/parallel-webpack#25]

**Comment by pago** [comment]
Is that the current behaviour?

**Comment by wKich** [comment]
I can't setup `maxConcurrentCallsPerWorker`. I think with less value I get more responsive output, in my case. I can do PR for that. And maybe add json-schema validation for options.

**Comment by pago** [comment]
That'd be great. Thank you!
