### ISSUE TITLE
Incorrect behavior with watch option.

### ISSUE THREAD

**Issue by wKich** [trivago/parallel-webpack#26]
For now webpack workers build and start watch only for first `maxConcurrentCallsPerWorker * maxConcurrentWorkers` variants. Rest variants never builds until we press Ctrl+C and stop watching first variants.

I don't know how to fix this.

**Comment by pago** [comment]
I'll close this for now as I don't think there is a way to fix it. To be honest, I'm not even sure if fixing this would help. Depending on project size, running multiple watchers in parallel might cause more trouble (cpu usage, memory usage, battery usage) than its worth.

Thank you for reporting!

**Comment by wKich** [comment]
Maybe we can use an external watch/poll and run compiler on every changes, and use webpack cache to improve rebuild process? But yeah, it's weird build all bundle variants while developing :)
