### ISSUE TITLE
After ctrl+c build/watch restarts

### ISSUE THREAD

**Issue by pwalczyszyn** [trivago/parallel-webpack#29]
After upgrading to 1.6.0 from 1.3.1 my build (with --watch arg) restarts in the background when I ctrl+c the currently running one. BTW I'm on webpack `2.2.0-rc.2`.

**Comment by maxmumford** [comment]
Any update on this? Can't really use parallel-webpack until this is sorted

**Comment by pago** [comment]
Just released the fix for this as 1.6.1

Please let me know if it works for you.

**Comment by maxmumford** [comment]
Works great, thanks!

**Comment by maxmumford** [comment]
@pago  looks like this is still happening if the build script runs into an error with --watch

**Comment by pago** [comment]
Did you try https://github.com/trivago/parallel-webpack#specifying-retry-limits (`-m` option) to disable that behaviour?

**Comment by maxmumford** [comment]
Ah yes that fixed it. It's a little counterintuitive to me that it retries by default but probably not worth fixing. Thanks for your support.
