### ISSUE TITLE
Update to webpack2

### ISSUE THREAD

**Issue by anilanar** [trivago/parallel-webpack#31]
Pretty please?

**Comment by pago** [comment]
Based on the discussion in #19 I believe it already works. Did you experience any particular issues with running Webpack 2 and parallel-webpack together?

**Comment by anilanar** [comment]
I think `package.json` needs to be updated:

`"webpack": "^1.12.9 || ^2.2.0"`

**Comment by pago** [comment]
We can do that but it already prefers the locally installed version: https://github.com/trivago/parallel-webpack/issues/19#issuecomment-264178851
So if you have version 2.2 installed locally in your project, parallel-webpack will detect and use it instead of its own version 1.
