### ISSUE TITLE
On complete hook

### ISSUE THREAD

**Issue by aramk** [trivago/parallel-webpack#39]
Is there any way to determine when building has been completed? I'm launching the app using `OpenBrowserPlugin` but I don't know when it's completed all parallel builds.

**Comment by aramk** [comment]
I tried using the Node.js API but the run() method callback and promise are only fired when `watch: false`.

**Comment by pago** [comment]
A Promise based API can't support `watch` mode. We could potentially add support for it for the callback style approach.
Would you like to try implementing this yourself? Would be very happy about a PR.

**Comment by natedanner** [comment]
#55 Added this functionality. In watch mode the callback is now fired once all configurations have been compiled once.
