### ISSUE TITLE
[Webpack 2] Using --optimize-minimize argument with parallel-webpack

### ISSUE THREAD

**Issue by softvar** [trivago/parallel-webpack#40]
I tried but failed to minimize my files

`parallel-webpack -p=1 --optimize-minimize --progress --colors --watch -- --env.mode=build`

&

`parallel-webpack -p=1 --progress --colors --watch -- --optimize-minimize --env.mode=build`

Any solution?

**Comment by pago** [comment]
We don't support most of the webpack related CLI arguments. You need to configure optimization as part of your `webpack.config.js`.

If we add support for some, we'd need to support all of them and would also have to ensure compatibility. For now we don't intend to support this option.

P.S.: Sorry for the delay, I was on vacation.

**Comment by carlescs** [comment]
As a crazy idea, would it be possible to add a generic parameter that added its values as parameters to webpack? Like this:

```
parallel-webpack -w "--optimize-minimize --progress --colors --watch -- --env.mode=build"
```

**Comment by pago** [comment]
We're not actually calling the CLI interface but rather just use the programmatic API instead so we'd still need to parse and transform those options.
