### ISSUE TITLE
freezed on parallel-webpack run on circleci

### ISSUE THREAD

**Issue by cordoval** [trivago/parallel-webpack#41]
while running on circleci the process completely stops on parallel-webpack

it never continues . I have to cancel the build. Is there anything i am missing?

**Comment by vansosnin** [comment]
Noticed the same in TeamCity (I don't think that CI service matters). On version 2.0.0 as well :(

**Comment by cordoval** [comment]
I think parallel-webpack is not really a solution, there is better ways to do this, if it aches it needs to be addressed differently.

**Comment by pago** [comment]
Can you identify any error message or anything to help diagnose the problem? Did you try running it with `-p=1` or the number of CPUs available to you? Perhaps we just don't detect the correct number of CPUs on circleci and TeamCity?

We're running `parallel-webpack` in Jenkins without any issues so I know it works on CI systems.

**Comment by cordoval** [comment]
on circleci the cpu count was 1 i think, yeah i know, i was just surveying the tools there.
I believe though there must be a more suitable solution to speed things up. I am not sure if this is it yet though. Thanks 👍
