### ISSUE TITLE
Support for dynamic configurations??

### ISSUE THREAD

**Issue by maheshambiga** [trivago/parallel-webpack#45]
Is it possible to pass configuration array to the 'run' method. Currently it only takes configuration file name(as string).
I have a scenario where I need to dynamically create configurations and kickstart webpack bundling.

**Comment by pago** [comment]
Hi @maheshambiga, this feature can unfortunately not be implemented as the Webpack config allows complex objects (such as class instances) to be defined and the only way to communicate with individual workers is through strings.

As we can't serialize the configuration without potentially losing some parts of it, we can't implement this feature.
