### ISSUE TITLE
Expose API that takes array of webpack configs

### ISSUE THREAD

**Issue by anilanar** [trivago/parallel-webpack#51]
Assume I have an array of unrelated, handcrafted webpack configurations. I would like to run them in parallel using `parallel-webpack` node.js API. For example if `run` function took an array of configs instead of config paths, it would somewhat work for me.

My proposal is to have a lower level API for running array of configs that is reused by the actual `run` function that takes config path.

**Comment by pago** [comment]
An array of config paths or of config objects? The latter is not possible, see also #45.

**Comment by anilanar** [comment]
Fair enough.
