### ISSUE TITLE
Skipping processes on Ubuntu

### ISSUE THREAD

**Issue by makamekm** [trivago/parallel-webpack#66]
It recompiles only the first task with --watch on Ubuntu. Windows & MacOS are good.

**Comment by efegurkan** [comment]
Hello, sorry for the late reply.

If possible can you explain more about the issue? Best would be a dummy repository to reproduce?

I  tried to reproduce in on my local with 4 entry points when I do changes it reruns the build related to change. Tried on fedora and it should work the same with Ubuntu.

**Comment by efegurkan** [comment]
Hey again, 

Unfortunately I couldn't reproduce it. Closing it for now.

If you still have problems with it please feel free to reopen. 

Cheers,
