### ISSUE TITLE
Can I pass the webpack config object instead of config path?

### ISSUE THREAD

**Issue by chuyik** [trivago/parallel-webpack#68]

**Comment by pago** [comment]
No, that is unfortunately not possible because the Webpack config object can't be serialized (it might contain instances of classes or functions).

**Comment by rohit-smpx** [comment]
@pago I agree with you on that. But when using https://github.com/trivago/parallel-webpack#nodejs-api then calling parallel-webpack.run() from inside a js file where I've dynamically created my config object according to some external variables (env, dir paths, etc) should be possible. It's possible with webpack.

I would be willing to submit a PR, but I'm not sure if I should base it on the new 3.0 branch or the current stable release (master)?

**Comment by rohit-smpx** [comment]
Oh! I had not thought of that. Thanks for explaining it.
