### ISSUE TITLE
No reference for 2.4.0 release

### ISSUE THREAD

**Issue by dpraul** [trivago/parallel-webpack#96]
Hi! Glad to see this repo is back alive. We got a notification that it has been updated on [npm to v2.4.0](https://www.npmjs.com/package/parallel-webpack/v/2.4.0), but there is no reference to that release here.

Given that the release time was around the time of the last commit (afeb3d325b046c12f4494f540321515f8cd43883), I'd assume they match, but please going forward remember to tag the releases! It's hard to trust a project's releases if there's no obvious trail.

**Comment by pago** [comment]
<img width="664" alt="Screenshot 2019-06-03 at 20 39 02" src="https://user-images.githubusercontent.com/193788/58825903-b6d53b00-863f-11e9-8036-d8385b93df99.png">

I'm sorry and sort of still waiting for the tag to be published. I'm not sure what went wrong with this release but I'll look into it.

**Comment by dpraul** [comment]
Hello! This is not resolved - there is still no reference to version 2.4.0 anywhere in the repo
